# Standardize sparse matrix

**Objective:**
* standardize a sparse matrix without losing sparsity

In [6]:
import numpy as np
import pandas as pd

from scipy.sparse import csr_matrix, csc_matrix
from sklearn.preprocessing import normalize, StandardScaler

In [2]:
A = csc_matrix([[1, 2, 0], [0, 0, 3], [4, 0, 5]]).astype(np.float64)

In [3]:
A.todense()

matrix([[ 1.,  2.,  0.],
        [ 0.,  0.,  3.],
        [ 4.,  0.,  5.]])

* `with_mean=False` is necessary for sparse matrices

In [4]:
StandardScaler(with_mean=False).fit_transform(A).todense()

matrix([[ 0.58834841,  2.12132034,  0.        ],
        [ 0.        ,  0.        ,  1.45999279],
        [ 2.35339362,  0.        ,  2.43332132]])

In [83]:
df = pd.DataFrame({'bla': [6, 7, 9]})

In [81]:
arr = [6, 7, 9]
mean = np.sum(arr) / 3

var = 0.0
for i in arr:
    var+=np.power(i - mean, 2)

var / 2

2.333333333333333

In [82]:
df[['bla']].std()

bla    4.017817
dtype: float64

In [ ]:
df['bla'].var

In [ ]:
df['bla'].var

In [ ]:
result = 0.0
for 

In [73]:
df['bla'].var()

2.333333333333333

In [42]:
df['bla'].var()

2.333333333333333

In [43]:
s = StandardScaler().fit(df)

In [52]:
s.var_

array([ 1.55555556])

In [38]:
s.mean_

array([ 7.])

In [64]:
s2 = StandardScaler(with_mean=False).fit(df)

In [68]:
s2.var_

array([ 1.55555556])

bla    6
foo    0
dtype: int64

In [91]:
np.log2((0.5 / 65000) * 1000000)

2.9434164716336326